// File generated by FlutterFire CLI.
// This is a placeholder - you'll need to replace with actual values from Firebase Console

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // TODO: Replace with your actual Firebase configuration

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBphcgJSWl8-cFZPubVyJDFa5c4yRbBQE',
    appId: '1:1067955332820:web:bb3bb9926be0f61ccebd41',
    messagingSenderId: '1067955332820',
    projectId: 'musclemax-ad6d4',
    authDomain: 'musclemax-ad6d4.firebaseapp.com',
    storageBucket: 'musclemax-ad6d4.firebasestorage.app',
    measurementId: 'G-DNMJ0QDCS3',
  );

  // Get these values from Firebase Console > Project Settings > Your apps

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDr-giMQQwsvzUicvuKa8DL7xQwEV4RRpc',
    appId: '1:1067955332820:android:59b5799e80a3d1f3cebd41',
    messagingSenderId: '1067955332820',
    projectId: 'musclemax-ad6d4',
    storageBucket: 'musclemax-ad6d4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'YOUR_IOS_API_KEY',
    appId: 'YOUR_IOS_APP_ID',
    messagingSenderId: 'YOUR_MESSAGING_SENDER_ID',
    projectId: 'YOUR_PROJECT_ID',
    storageBucket: 'YOUR_PROJECT_ID.appspot.com',
    iosClientId: 'YOUR_IOS_CLIENT_ID',
    iosBundleId: 'com.example.musclemax',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'YOUR_MACOS_API_KEY',
    appId: 'YOUR_MACOS_APP_ID',
    messagingSenderId: 'YOUR_MESSAGING_SENDER_ID',
    projectId: 'YOUR_PROJECT_ID',
    storageBucket: 'YOUR_PROJECT_ID.appspot.com',
    iosClientId: 'YOUR_MACOS_CLIENT_ID',
    iosBundleId: 'com.example.musclemax',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBBphcgJSWl8-cFZPubVyJDFa5c4yRbBQE',
    appId: '1:1067955332820:web:0db77e19c7b70c7dcebd41',
    messagingSenderId: '1067955332820',
    projectId: 'musclemax-ad6d4',
    authDomain: 'musclemax-ad6d4.firebaseapp.com',
    storageBucket: 'musclemax-ad6d4.firebasestorage.app',
    measurementId: 'G-XSS8XEZD0X',
  );

}